---
- name: Playbook web
  hosts: web
  tasks:
    - name: Installer un serveur web
      package:
        name: nginx
        state: present

    - name: Vérifier le démarrage du serveur web
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Télécharger Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/wp.tar.gz

    - name: Désarchive Wordpress
      unarchive:
        src: /var/www/html/wp.tar.gz
        dest: /var/www/html/
        remote_src: yes