---

- name: Playbook PHP
  hosts: php
  handlers:
  - name: recharger systemctl
    systemd:
      daemon_reload: true
  - name: Redémarrer php
    service:
      name: "php{{ php_version }}-fpm"
      state: restarted
  tasks:
  - name: Installer PHP-FPM
    package:
      name:
      - "php{{ php_version }}-fpm"
      - php-mysql
      state: latest

  - name: Vérifier le démarrage de php
    service:
      name: "php{{ php_version }}-fpm"
      state: started
      enabled: yes

  - name: Envoi de la configuration php
    template: 
      src: files/fpm.conf
      dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    notify: Redémarrer php
    
  - name: Installer le client NFS
    package:
      name: nfs-common
      state: latest
  
  - name: Créer le point de montage
    file:
      path: "{{ wordpress_path }}"
      state: directory
  
  - name: monter le partage nfs
    mount:
      fstype: nfs
      path: "{{ wordpress_path }}"
      src: "{{ hostvars[groups['web'][0]]['ansible_host'] }}:{{ wordpress_path }}"
      state: mounted
      opts: "_netdev,x-systemd.after=php{{ php_version }}-fpm.service"
  
  - name: Reconfiguer les services (1)
    file:
      path: "/etc/systemd/system/php{{ php_version }}-fpm.service.d/"
      state: directory
  
  - name: Reconfiguer les services (2)
    template:
      src: files/prestart.conf
      dest: "/etc/systemd/system/php{{ php_version }}-fpm.service.d/prestart.conf"
    notify: recharger systemctl
