---
- name: Playbook web
  hosts: web
  tasks:
    - name: Désinstaller Apache
      package:
        name: apache2*
        state: absent

    - name: Installer un serveur web
      package:
        name: nginx
        state: present

    - name: Vérifier le démarrage du serveur web
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Désarchive Wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
        creates: /var/www/html/wordpress