---

- name: Playbook PHP
  hosts: php
  tasks:
  - name: Installer PHP-FPM
    package:
      name: php-fpm
      state: latest

  - name: Vérifier le démarrage de php
    service:
      name: php8.2-fpm
      state: started
      enabled: yes

  - name: Envoi de la configuration php
    template: 
      src: files/fpm.conf
      dest: /etc/php/8.2/fpm/pool.d/www.conf
    register: php_conf

  - name: Redémarrer php
    service:
      name: php8.2-fpm
      state: restarted
    when: php_conf.changed
    
  - name: Installer le client NFS
    package:
      name: nfs-common
      state: latest
  
  - name: Créer le point de montage
    file:
      path: /var/www/html/wordpress
      state: directory
  
  - name: monter le partage nfs
    mount:
      fstype: nfs
      path: /var/www/html/wordpress
      src: "{{ hostvars[groups['web'][0]]['ansible_host'] }}:/var/www/html/wordpress"
      state: mounted
      opts: defaults